### PR TITLE
Github action to bundle app and upload installer for Mac, Windows & Linux

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Hi Russell, I've been tinkering with github actions to automatically build briefcase apps. I think it might be nice to include an example of this type of action in the traveltips repository to serve as a how-to guide for other people.

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
Note: The ubuntu build here fails for briefcase versions 0.3.2 and 0.3.3 - I'm not sure why. The bare-bones Toga hello world app doesn't fail in either of these conditions ([see here](https://github.com/GenevieveBuckley/pyconau2020-toga-helloworld/actions)). Presumably traveltips is doing something extra and fancy on top of that?

**Review by freakboy3742 — APPROVED** [review]
Couldn't agree more about this being a great addition; it's been on my wishlist for a while.

Interestingly, it makes it really clear that beeware/briefcase#424 would be a great thing to add - that would simplify the last few pieces of the build action considerably. Adding `--nosign` support for other platforms (even if it's no-op) would also simplify things nicely. 

That todo list keeps getting longer... :-)

**Comment by freakboy3742** [comment]
Ah - I worked out what is going on with the Linux build: `pyproject.toml` doesn't have any of the Linux system dependencies defined. I would have generated `pyproject.toml` before the move to Docker-based packaging.

**Comment by GenevieveBuckley** [comment]
Thanks!

Are you able to download, install, and run traveltips [Mac artifact from here](https://github.com/freakboy3742/traveltips/actions/runs/245842025)?

**Comment by GenevieveBuckley** [comment]
I ask because I'm getting inconsistent behaviour across platforms and methods of launching the app.

On Mac:
* Working: `briefcase dev` from the source repo
* Working: `briefcase run` from the source repo
* Not working for me: downloading the Mac installer uploaded as a github actions artifact is ok, but then I can't unzip it to install. Is this happening for you too?

On Windows:
* Working: `briefcase dev` from the source repo.
* Not working: `briefcase run` from the source repo. It says `[traveltips] Starting app...` and then just returns you to the terminal. There's no error message, and no window launched.
* Not working: downloading the Windows installer uploaded as a github actions artifact is ok, and it also seems to go through the installation wizard just fine too. But when you actually try to launch the app nothing happens (similar to what I saw with `briefcase run` earlier)

I don't have a linux machine handy to test this out on.

**Comment by GenevieveBuckley** [comment]
I ask because I'm getting inconsistent behaviour across platforms and methods of launching the app.

On Mac:
* Working: `briefcase dev` from the source repo
* Working: `briefcase run` from the source repo
* Not working for me: downloading the Mac installer uploaded as a github actions artifact is ok, but then I can't unzip it to install. Is this happening for you too?

On Windows:
* Working: `briefcase dev` from the source repo.
* Not working: `briefcase run` from the source repo. It says `[traveltips] Starting app...` and then just returns you to the terminal. There's no error message, and no window launched.
* Not working: downloading the Windows installer uploaded as a github actions artifact is ok, and it also seems to go through the installation wizard just fine too. But when you actually try to launch the app nothing happens (similar to what I saw with `briefcase run` earlier)

I don't have a linux machine handy to test this out on.

**Pull request merged**
